// src/helpers/baseAnalogies.js

export const baseAnalogies = {
  inches: [
    { value: 1, text: "about the width of a quarter" },
    { value: 2, text: "the length of a standard paperclip" },
    { value: 3, text: "the height of a golf tee" },
    { value: 4, text: "the length of a crayon" },
    { value: 5, text: "the height of a soda can" },
    { value: 6, text: "the length of a dollar bill" },
    { value: 7, text: "the width of a medium-sized tablet" },
    { value: 8, text: "the diameter of a small plate" },
    { value: 9, text: "the length of a standard kitchen knife" },
    { value: 10, text: "the width of a piece of printer paper" },
    { value: 11, text: "the height of a standard sheet of printer paper" },
    { value: 12, text: "the average height of an apartment room" },
  ],
  feet: [
    { value: 1, text: "the length of a ruler" },
    { value: 2, text: "the height of a standard office desk" },
    { value: 3, text: "the height of a standard countertop" },
    { value: 4, text: "the width of a typical single bed" },
    { value: 5, text: "the length of a typical snowboard" },
    { value: 6, text: "the height of a Christmas tree" },
    { value: 7, text: "the height of a basketball hoop" },
    { value: 8, text: "the height of a room" },
    { value: 9, text: "the length of a large surfboard" },
    { value: 10, text: "the height of a one-story building" },
    { value: 11, text: "the height of a typical giraffe" },
    { value: 12, text: "the length of a garden hose" },
    { value: 13, text: "the height of a two-story building" },
    { value: 14, text: "the length of a small boat" },
    { value: 15, text: "the height of a streetlight" },
    { value: 16, text: "the length of a parking space" },
    { value: 17, text: "the height of a power pole" },
    { value: 18, text: "the length of a long hallway" },
    { value: 19, text: "the height of a large tree" },
    { value: 20, text: "the length of a bus" },
    { value: 21, text: "the height of a two-story house" },
    { value: 22, text: "the length of a semi-truck" },
    { value: 23, text: "the height of a wind turbine" },
    { value: 24, text: "the length of a train car" },
    { value: 25, text: "the height of a small skyscraper" },
    { value: 26, text: "the length of a yacht" },
    { value: 27, text: "the height of a large flagpole" },
    { value: 28, text: "the length of a basketball court" },
    { value: 29, text: "the height of a Ferris wheel" },
    { value: 30, text: "the length of a small airplane" },
  ],
  patterns: {
    feet: "the length of {count} {unit}",
    mile: "the length of {count} mile{plural}",
  },
};
